**TensorFlow Fundamentals Exercises**
=====================================

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

2. Find the shape, rank and size of the tensors you created in 1.

3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

4. Multiply the two tensors you created in 3 using matrix multiplication.

5. Multiply the two tensors you created in 3 using dot product.

6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

7. Find the min and max values of the tensor you created in 6 along the first axis.

8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

10. One-hot encode the tensor you created in 9.

-----------------------------------------------------------------------------------------------------
                                                Solution                                                        

In [1]:
import tensorflow as tf

In [2]:
Scalar = tf.constant(5)
vector = tf.constant([1,2,3,4])
matrix = tf.constant([[1,2],[3,4]])
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
Scalar, vector , matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 <tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]])>)

In [9]:
print("Scalar shape:", Scalar.shape)
print("Scalar rank:", Scalar.shape.rank)
print("Scalar size:", tf.size(Scalar))

print("Vector shape:", vector.shape)
print("Vector rank:", vector.shape.rank)
print("Vector size:", tf.size(vector))

print("Matrix shape:", matrix.shape)
print("Matrix rank:", matrix.shape.rank)
print("Matrix size:", tf.size(matrix))

print("Tensor shape:", tensor.shape)
print("Tensor rank:", tensor.shape.rank)
print("Tensor size:", tf.size(tensor))

Scalar shape: ()
Scalar rank: 0
Scalar size: tf.Tensor(1, shape=(), dtype=int32)
Vector shape: (4,)
Vector rank: 1
Vector size: tf.Tensor(4, shape=(), dtype=int32)
Matrix shape: (2, 2)
Matrix rank: 2
Matrix size: tf.Tensor(4, shape=(), dtype=int32)
Tensor shape: (2, 2, 2)
Tensor rank: 3
Tensor size: tf.Tensor(8, shape=(), dtype=int32)


In [20]:
tensor1 = tf.random.uniform([5, 300])
tensor2 = tf.random.uniform([5, 300])
tensor1, tensor2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.59520733, 0.06266105, 0.92026293, ..., 0.49019134, 0.6740171 ,
         0.29855108],
        [0.43805993, 0.8785441 , 0.11268973, ..., 0.83740747, 0.86660266,
         0.65028524],
        [0.4500463 , 0.7305137 , 0.05319834, ..., 0.64534426, 0.04847312,
         0.14000702],
        [0.25237334, 0.6803416 , 0.6739547 , ..., 0.6132461 , 0.38984323,
         0.12271798],
        [0.11355066, 0.87089074, 0.28845286, ..., 0.3735745 , 0.73592687,
         0.23085809]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.39761555, 0.19161153, 0.9583901 , ..., 0.16368604, 0.24390781,
         0.15387058],
        [0.5393468 , 0.09327459, 0.4078697 , ..., 0.19760263, 0.21027303,
         0.38184595],
        [0.6575408 , 0.09120941, 0.23230982, ..., 0.11451912, 0.6841862 ,
         0.9715229 ],
        [0.8918413 , 0.23455107, 0.9187335 , ..., 0.17914319, 0.542997  ,
         0.1924907 ],
        [0.51706

In [25]:
result = tf.matmul(tensor1, tf.transpose(tensor2))
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.87295 , 74.83064 , 75.15852 , 74.093094, 73.97275 ],
       [75.27762 , 71.99204 , 72.86113 , 73.03406 , 71.72366 ],
       [79.2313  , 71.96298 , 75.076645, 72.761566, 72.52217 ],
       [75.96359 , 70.93398 , 72.89791 , 74.2335  , 70.70001 ],
       [77.13995 , 70.69176 , 76.66206 , 71.60069 , 73.82054 ]],
      dtype=float32)>

In [30]:
result = tf.tensordot(tensor1, tensor2, axes=0)


In [31]:
tensor = tf.random.uniform([224, 224, 3])

In [32]:
min_value = tf.reduce_min(tensor, axis=0)
max_value = tf.reduce_max(tensor, axis=0)

In [35]:
tensor = tf.random.uniform([1, 224, 224, 3])
squeezed_tensor = tf.squeeze(tensor)

In [36]:
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
max_index = tf.argmax(tensor)

In [37]:
one_hot_tensor = tf.one_hot(tensor, depth=10)
one_hot_tensor

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>