**Welcome to TensorFlow: A Beginner's Guide**

**What is TensorFlow?**

TensorFlow is a powerful tool that helps us build and use machine learning models. It's like a big library that has many useful functions that we can use to make our lives easier. You can think of it like a toolbox that has many tools that we can use to build and train our models.

**Why Use TensorFlow?**

Instead of building everything from scratch, we can use TensorFlow to make our lives easier. It has many common machine learning functions that we can use, so we don't have to start from zero.

**What We're Going to Cover**

TensorFlow is a big topic, but don't worry, we're going to take it one step at a time. We'll cover the basics of TensorFlow, including:

* What are tensors and how do we create them?
* How do we get information from tensors?
* How do we manipulate tensors?
* How do tensors work with NumPy?
* How do we use a special function called `@tf.function` to make our code faster?
* How do we use GPUs with TensorFlow?
* Some exercises to try on your own

**Important Notes**

* Many of the things we'll cover will happen automatically when we build a model, but it's good to know what's going on behind the scenes.
* If you see a TensorFlow function that you don't understand, you can always look it up in the documentation. The documentation is like a big manual that explains how everything works. You can find it here:
     https://www.tensorflow.org/api_docs/python/ .

In [8]:
import tensorflow as tf
print(tf.__version__)

2.16.1


# Tensors

A **tensor** is a mathematical object that represents a multi-dimensional array of numerical values.

Think of a tensor like a container that holds a set of values, similar to a matrix or an array. However, tensors can have more than two dimensions, unlike matrices, which are limited to two dimensions.

Here's a simple analogy to help you understand tensors:

* A scalar is a single value, like a number (e.g., 5).
* A vector is a 1-dimensional array of values, like a list of numbers (e.g., [1, 2, 3, 4, 5]).
* A matrix is a 2-dimensional array of values, like a table of numbers (e.g., [[1, 2], [3, 4]]).
* A tensor is a multi-dimensional array of values, like a cube or a higher-dimensional structure of numbers (e.g., [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]).

Tensors are used to represent complex data structures in machine learning and deep learning, such as:

* Images: A color image can be represented as a 3-dimensional tensor, with dimensions for height, width, and color channels (e.g., RGB).
* Audio: A sound wave can be represented as a 2-dimensional tensor, with dimensions for time and frequency.
* Text: A sentence or a document can be represented as a high-dimensional tensor, with dimensions for words, sentences, and semantic meaning.

In TensorFlow, tensors are the fundamental data structure used to represent inputs, outputs, and intermediate results of machine learning models. TensorFlow provides various operations and functions to manipulate and transform tensors, which enables the creation of complex machine learning models.

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Cheack the number of dimentions
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
# Cheack the number of dimentions
vector.ndim

1

In [6]:
# Create a matrix
matix = tf.constant([[10,7],[7,10]])
matix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
matix.ndim

2